export const BY_DATE = 'BY_DATE'
export const BY_SCORE = 'BY_SCORE'

export const UP_VOTE = 'upVote'
export const DOWN_VOTE = 'downVote'

export const ADD_POST = 'ADD_POST'
export const GET_POSTS = 'GET_POSTS'
export const EDIT_POST = 'EDIT_POST'
export const DELETE_POST = 'DELETE_POST'
export const ADD_COMMENT = 'ADD_COMMENT'
export const EDIT_COMMENT = 'EDIT_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'
export const GET_POST_BY_ID = 'GET_POST_BY_ID'
export const GET_CATEGORIES = 'GET_CATEGORIES'
export const GET_COMMENTS_BY_POST_ID = 'GET_COMMENTS_BY_POST_ID'