const BY_DATE = 'BY_DATE'
const BY_SCORE = 'BY_SCORE'

const ADD_POST = 'ADD_POST'
const GET_POSTS = 'GET_POSTS'
const EDIT_POST = 'EDIT_POST'
const GET_POST_BY_ID = 'GET_POST_BY_ID'
const GET_CATEGORIES = 'GET_CATEGORIES'
const GET_COMMENTS_BY_POST_ID = 'GET_COMMENTS_BY_POST_ID'

module.exports = {
    BY_DATE,
    BY_SCORE,

    ADD_POST,
    GET_POSTS,
    EDIT_POST,
    GET_POST_BY_ID,
    GET_CATEGORIES,
    GET_COMMENTS_BY_POST_ID,
}